# Site settings
title: The New Adventures of Scrapinold Dooington, the Later Years
description: "A comic chronicling the crazy post-retirement adventures of the world-renowned detective Scrapinold Dooington, alongside with a lovable cast of characters."
baseurl: ""
url: ""
github_username:  scrapinold

# Build settings
markdown: kramdown
permalink: none

gems:
- jekyll-redirect-from
- jekyll-sitemap